CP_TO_PROVINCE = {
    "01": "Álava",
    "02": "Albacete",
    "03": "Alicante",
    "04": "Almería",
    "05": "Ávila",
    "06": "Badajoz",
    "07": "Illes Balears",
    "08": "Barcelona",
    "09": "Burgos",
    "10": "Cáceres",
    "11": "Cádiz",
    "12": "Castellón",
    "13": "Ciudad Real",
    "14": "Córdoba",
    "15": "A Coruña",
    "16": "Cuenca",
    "17": "Girona",
    "18": "Granada",
    "19": "Guadalajara",
    "20": "Gipuzkoa",
    "21": "Huelva",
    "22": "Huesca",
    "23": "Jaén",
    "24": "León",
    "25": "Lleida",
    "26": "La Rioja",
    "27": "Lugo",
    "28": "Madrid",
    "29": "Málaga",
    "30": "Murcia",
    "31": "Navarra",
    "32": "Ourense",
    "33": "Asturias",
    "34": "Palencia",
    "35": "Las Palmas",
    "36": "Pontevedra",
    "37": "Salamanca",
    "38": "Santa Cruz de Tenerife",
    "39": "Cantabria",
    "40": "Segovia",
    "41": "Sevilla",
    "42": "Soria",
    "43": "Tarragona",
    "44": "Teruel",
    "45": "Toledo",
    "46": "Valencia",
    "47": "Valladolid",
    "48": "Bizkaia",
    "49": "Zamora",
    "50": "Zaragoza",
    "51": "Ceuta",
    "52": "Melilla"
}

PROVINCE_TO_REGION = {
    "A Coruña": "Galicia",
    "Álava": "País Vasco",
    "Albacete": "Castilla-La Mancha",
    "Alicante": "Comunidad Valenciana",
    "Almería": "Andalucía",
    "Asturias": "Principado de Asturias",
    "Ávila": "Castilla y León",
    "Badajoz": "Extremadura",
    "Barcelona": "Cataluña",
    "Burgos": "Castilla y León",
    "Cáceres": "Extremadura",
    "Cádiz": "Andalucía",
    "Cantabria": "Cantabria",
    "Castellón": "Comunidad Valenciana",
    "Ciudad Real": "Castilla-La Mancha",
    "Córdoba": "Andalucía",
    "Cuenca": "Castilla-La Mancha",
    "Girona": "Cataluña",
    "Granada": "Andalucía",
    "Guadalajara": "Castilla-La Mancha",
    "Gipuzkoa": "País Vasco",
    "Huelva": "Andalucía",
    "Huesca": "Aragón",
    "Illes Balears": "Islas Baleares",
    "Jaén": "Andalucía",
    "La Rioja": "La Rioja",
    "Las Palmas": "Canarias",
    "León": "Castilla y León",
    "Lleida": "Cataluña",
    "Lugo": "Galicia",
    "Madrid": "Comunidad de Madrid",
    "Málaga": "Andalucía",
    "Murcia": "Región de Murcia",
    "Navarra": "Navarra",
    "Ourense": "Galicia",
    "Palencia": "Castilla y León",
    "Pontevedra": "Galicia",
    "Salamanca": "Castilla y León",
    "Santa Cruz de Tenerife": "Canarias",
    "Segovia": "Castilla y León",
    "Sevilla": "Andalucía",
    "Soria": "Castilla y León",
    "Tarragona": "Cataluña",
    "Teruel": "Aragón",
    "Toledo": "Castilla-La Mancha",
    "Valencia": "Comunidad Valenciana",
    "Valladolid": "Castilla y León",
    "Bizkaia": "País Vasco",
    "Zamora": "Castilla y León",
    "Zaragoza": "Aragón",
    "Ceuta": "Ceuta",
    "Melilla": "Melilla"
}

PROVINCES = [
    # ESPAÑA
    "Alava", "Albacete", "Alicante", "Almeria", "Asturias", "Avila",
    "Badajoz", "Barcelona", "Burgos", "Caceres", 
    "Cadiz", "Cantabria", "Castellon", "Ceuta", "Ciudad-Real", 
    "Cordoba", "Cuenca", "Fuerteventura",
    "Gerona", "Granada", "Guadalajara", "Guipuzcoa", 
    "Huelva", "Huesca", "Baleares", "Jaen",
    "Coruna", "Rioja", "Leon", "Lerida", "Lugo", 
    "Madrid", "Malaga", "Melilla", "Murcia", 
    "Navarra", "Orense", "Palencia", "Pontevedra",
    "Salamanca", "Segovia", "Sevilla", "Soria",
    "Tarragona", "Teruel", "Toledo",
    "Valencia", "Valladolid", "Vizcaya",
    "Zamora", "Zaragoza",
]

LIDL_SERVICES = {
    "brxe-hlpeef brxe-svg": "Aparcamiento para discapacitados", 
    "brxe-ebqxhm brxe-svg": "Panadería", 
    "brxe-kvgerg brxe-svg": "Lockers",
    "brxe-cvyfzz brxe-svg": "Parking", 
    "brxe-wjilaa brxe-svg": "Lidl Plus",
    "brxe-dzvwzr brxe-svg": "Promociones de alimentación y bazar",
    "brxe-jhyrfw brxe-svg": "Punto de recarga para coches eléctricos", 
}

GADIS_SERVICES = {
    "cafeteria": "Cafetería",
    "parking": "Parking",
    "domicilio": "Servicio a domicilio",
    "parkingDiscapacitados": "Parking para discapacitados",
    "parkingVehiculos": "Parking para vehículos",
    "taquilla": "Taquilla",
    "entrada": "Entrada",
    "ascensor": "Ascensor",
    "aseos": "Aseos",
    "aseosRuedas": "Aseos adaptados para sillas de ruedas",
    "entrega": "Entrega a domicilio",
    "recogida": "Recogida en tienda",
    "cafe": "Máquina de café",
    "plastico": "Contenedor de plástico",
    "botellas": "Contenedor de botellas",
    "latas": "Contenedor de latas",
    "pilas": "Punto de recogida de pilas",
    "aparatos": "Recogida de pequeños aparatos eléctricos",
    "panaderia": "Panadería",
    "cortadora": "Cortadora de fiambre",
    "pescaderia": "Pescadería",
    "carniceria": "Carnicería",
    "charcuteria": "Charcutería",
    "zumo": "Máquina de zumo",
    "preparada": "Comida preparada",
    "pagos": "Pagos con tarjeta",
    "carrito": "Carrito de compra",
    "autocobro": "Caja de autocobro",
    "wifi": "Wi-Fi gratuito"
}

MAX_WAIT = 10